# SPDX-License-Identifier: MIT
# Copyright (c) 2026 AgenticEconLab
"""
IdeationTeam stage output schemas.

Canonical Pydantic models for the Ideation pipeline. All stage files MUST
import from here — no inline model definitions allowed (V0.4 policy).
"""

from typing import Any, Dict, List, Optional, Tuple
from pydantic import BaseModel, Field

from shared.schema_coerce import LLMCoercedModel


# ============================================================================
# Stage 1: Sourcing — Output Models
# ============================================================================

class LiteratureItem(BaseModel):
    """A literature item found by sourcing agents."""
    title: str = Field(description="Title of the paper/document")
    authors: List[str] = Field(description="List of authors")
    abstract: str = Field(default="No abstract available", description="Abstract or summary")
    url: str = Field(description="URL or identifier")
    source: str = Field(description="Source database/repository")
    agent: str = Field(description="Agent that found this item")
    year: Optional[int] = Field(default=None, description="Publication year")
    venue: Optional[str] = Field(default=None, description="Publication venue (journal/repository), never the search provider")
    literature_type: str = Field(default="academic", description="Type: academic, grey, preprint")
    citation_count: Optional[int] = Field(default=None, description="Number of citations")
    relevance_score: Optional[float] = Field(default=None, description="Relevance score (0-1)")


class SearchQuery(LLMCoercedModel):
    """Refined search queries generated by agents."""
    queries: List[str] = Field(description="List of refined search queries")
    keywords: List[str] = Field(description="Key terms to search for")
    focus_areas: List[str] = Field(description="Specific focus areas")


class SourcingFeedback(BaseModel):
    """Human feedback on sourcing results (HITL modes, Stage 1)."""
    round_number: int = Field(description="Feedback round number")
    relevant_papers: List[str] = Field(description="Titles of relevant papers", default_factory=list)
    irrelevant_papers: List[str] = Field(description="Titles of irrelevant papers", default_factory=list)
    missing_topics: List[str] = Field(description="Topics that should be explored more", default_factory=list)
    additional_keywords: List[str] = Field(description="Additional keywords to include", default_factory=list)
    comments: str = Field(description="General comments and guidance", default="")


class SourcingStageOutput(BaseModel):
    """Complete output of Stage 1: Sourcing."""
    literature_items: List[LiteratureItem] = Field(description="All literature items found")
    search_queries: List[SearchQuery] = Field(default_factory=list, description="Search queries used")
    metadata: Dict = Field(default_factory=dict, description="Stage metadata")


# ============================================================================
# Stage 2: Refinement — Output Models
# ============================================================================

class ResearchConcept(LLMCoercedModel):
    """A research concept generated by the Ideator agent."""
    concept_title: str = Field(description="Short title for the concept")
    description: str = Field(description="Detailed description of the concept")
    key_themes: List[str] = Field(description="Key themes or topics")
    literature_support: List[str] = Field(description="Paper titles that support this concept")
    novelty_score: Optional[float] = Field(default=None, description="Novelty score (0-1)")
    reasoning: Optional[Any] = Field(default=None, description="Evidence weighed before reaching this concept")
    alternatives_considered: Optional[List[Any]] = Field(
        default=None, description="Alternative framings rejected, each with a brief reason")
    novelty_claim: Optional[Any] = Field(
        default=None, description="Explicit statement of what is novel and what risk it carries")
    novelty_components: Optional[Dict[str, Any]] = Field(
        default=None, description="Auditable sub-scores that compose novelty_score")


class EvolutionTrace(LLMCoercedModel):
    """Tracks how a research question evolved from source ideas."""
    source_ideas: List[str] = Field(default_factory=list, description="Source ideas from ideation")
    refinement_steps: List[str] = Field(default_factory=list, description="Steps taken to refine")
    alternatives_considered: List[str] = Field(default_factory=list, description="Rejected alternatives")


class ResearchQuestion(LLMCoercedModel):
    """A refined research question."""
    question: str = Field(description="The research question")
    rationale: str = Field(description="Why this question is important")
    methodology_hints: List[str] = Field(description="Suggested methodological approaches")
    related_concepts: List[str] = Field(description="Related concept titles")
    feasibility_score: Optional[float] = Field(default=None, description="Feasibility score (0-1)")
    selection_rationale: Optional[str] = Field(default=None, description="Why selected over alternatives")
    assumptions: Optional[List[str]] = Field(default=None, description="Underlying assumptions")
    limitations: Optional[List[str]] = Field(default=None, description="Limitations")
    evolution_trace: Optional[EvolutionTrace] = Field(default=None, description="Evolution from source ideas")
    reasoning: Optional[Any] = Field(default=None, description="Evidence weighed before formulating this question")
    alternatives_considered: Optional[List[Any]] = Field(
        default=None, description="Alternative question formulations rejected, each with a brief reason")
    feasibility_components: Optional[Dict[str, Any]] = Field(
        default=None, description="Auditable sub-scores that compose feasibility_score")


class ConceptList(LLMCoercedModel):
    """LLM response wrapper for a list of research concepts."""
    concepts: List[ResearchConcept] = Field(description="List of research concepts")


class QuestionList(LLMCoercedModel):
    """LLM response wrapper for a list of research questions."""
    questions: List[ResearchQuestion] = Field(description="List of research questions")


class HumanFeedback(BaseModel):
    """Human feedback on concepts/questions (HITL modes)."""
    round_number: int = Field(description="Feedback round number")
    promising_items: List[str] = Field(description="Promising concepts/questions", default_factory=list)
    weak_items: List[str] = Field(description="Weak or unfeasible items", default_factory=list)
    missing_angles: List[str] = Field(description="Missing perspectives or angles", default_factory=list)
    focus_directions: List[str] = Field(description="Directions to focus on", default_factory=list)
    comments: str = Field(description="General comments and guidance", default="")


class StageTransitionSummary(BaseModel):
    """Tracks the transition from sourcing to refined questions."""
    sourcing_input_count: int = Field(description="Number of papers from the sourcing stage")
    refinement_clusters: int = Field(description="Number of thematic concept clusters identified during refinement")
    final_questions: int = Field(description="Number of final research questions produced")
    filtering_rationale: str = Field(description="Explanation of how items were filtered from sourcing to final questions")


class RefinementStageOutput(BaseModel):
    """Complete output of Stage 2: Refinement."""
    concepts: List[ResearchConcept] = Field(description="Generated research concepts")
    questions: List[ResearchQuestion] = Field(description="Refined research questions")
    metadata: Dict = Field(default_factory=dict, description="Stage metadata")


# ============================================================================
# Stage 3: Integration — Output Models
# ============================================================================

class ContextualizedQuestion(LLMCoercedModel):
    """A research question with theoretical context."""
    question: str = Field(description="The research question")
    theoretical_framework: str = Field(description="Theoretical framework and positioning")
    literature_gaps: List[str] = Field(description="Specific gaps in literature this addresses")
    contribution: str = Field(description="Expected contribution to the field")
    related_theories: List[str] = Field(description="Related theoretical perspectives")
    priority_score: Optional[float] = Field(default=None, description="Priority score (0-1)")
    gap_severity: Optional[Any] = Field(
        default=None, description="How severe/underexplored the gap is: low | medium | high")
    reasoning: Optional[Any] = Field(default=None, description="Evidence weighed when framing this question")
    alternatives_considered: Optional[List[Any]] = Field(
        default=None, description="Alternative theoretical framings rejected, each with a brief reason")
    priority_components: Optional[Dict[str, Any]] = Field(
        default=None, description="Auditable sub-scores that compose priority_score")
    source_id: Optional[Any] = Field(
        default=None, description="Id (Q1..Qn) of the input question this one reformulates")
    ancestry: Optional[str] = Field(
        default=None, description="Deterministic ancestry check: accepted | reformulated | carried_forward")
    ancestry_similarity: Optional[float] = Field(
        default=None, description="Content-word similarity to the cited source (None if carried forward unclaimed)")


class PrioritizedQuestion(LLMCoercedModel):
    """A final prioritized research question after synthesis."""
    question: str = Field(description="The synthesized research question")
    theoretical_framework: str = Field(description="Theoretical framework")
    rationale: str = Field(description="Comprehensive rationale")
    methodology: List[str] = Field(description="Recommended methodologies")
    expected_impact: str = Field(description="Expected impact and contribution")
    feasibility: str = Field(description="Feasibility assessment")
    priority_rank: Optional[int] = Field(default=None, description="Priority ranking (1=highest)")
    priority_score: Optional[float] = Field(default=None, description="Priority score (0-1)")
    reasoning: Optional[Any] = Field(default=None, description="Evidence weighed when prioritizing this question")
    alternatives_considered: Optional[List[Any]] = Field(
        default=None, description="Other questions/rankings considered and rejected, each with a brief reason")
    topic_overlap: Optional[float] = Field(
        default=None, description="Share of the seed topic's content words found in the question (deterministic)")
    on_topic: Optional[bool] = Field(
        default=None, description="Deterministic seed-topic adherence check (None = no seed topic)")
    source_id: Optional[Any] = Field(
        default=None, description="Id (Q1..Qn) of the input question this one reformulates")
    ancestry: Optional[str] = Field(
        default=None, description="Deterministic ancestry check: accepted | reformulated | carried_forward")
    ancestry_similarity: Optional[float] = Field(
        default=None, description="Content-word similarity to the cited source (None if carried forward unclaimed)")


class IntegrationFeedback(BaseModel):
    """Human feedback during integration stage (HITL modes)."""
    round_number: int = Field(description="Feedback round number")
    questions_to_merge: List[Tuple[int, int]] = Field(
        description="Pairs of question indices to merge",
        default_factory=list
    )
    questions_to_discard: List[int] = Field(
        description="Indices of questions to discard",
        default_factory=list
    )
    questions_to_prioritize: List[int] = Field(
        description="Indices of questions to prioritize",
        default_factory=list
    )
    additional_guidance: str = Field(
        description="Additional guidance for refinement",
        default=""
    )


class ContextualizedQuestionList(LLMCoercedModel):
    """LLM response wrapper for a list of contextualized questions."""
    questions: List[ContextualizedQuestion] = Field(description="List of contextualized questions")


class PrioritizedQuestionList(LLMCoercedModel):
    """LLM response wrapper for a list of prioritized questions."""
    questions: List[PrioritizedQuestion] = Field(description="List of prioritized questions")


class IntegrationStageOutput(BaseModel):
    """Complete output of Stage 3: Integration."""
    contextualized_questions: List[ContextualizedQuestion] = Field(
        default_factory=list, description="Contextualized questions (intermediate)")
    prioritized_questions: List[PrioritizedQuestion] = Field(
        description="Final prioritized questions")
    metadata: Dict = Field(default_factory=dict, description="Stage metadata")
